[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-scripts",
    "npm ci --include=dev"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan package:discover --ansi"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
