providers = ["..."]

[phases.setup]
nixPkgs = ["...", "php82", "php82Packages.composer", "nodejs-18_x"]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev",
    "npm install",
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[phases.deploy]
cmds = ["php artisan migrate --force"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
